apiVersion: v2
name: azure-devops-agent
description: Dockerized build agent for Azure DevOps
type: application
version: 2.0.0
appVersion: "3.232.3"
keywords:
  - azure devops
  - build agent
  - dockerized agent
  - azure devops agent on kubernetes
home: "https://github.com/asilbek99/azure-devops-agent-on-kubernetes"
sources:
  - "https://github.com/asilbek99/azure-devops-agent-on-kubernetes"

annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: GitHub
      url: https://github.com/asilbek99/azure-devops-agent-on-kubernetes
