name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/azure-devops-agent:latest

  build-and-push-helm:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Helm
        uses: azure/setup-helm@v1

      - name: Package Helm Chart
        run: helm package ./chart --destination ./helm-package

      - name: Upload Helm chart to GitHub Packages
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: ./helm-package
          token: ${{ secrets.GITHUB_TOKEN }}
